### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by AbstractRamen** [AbstractRamen/FantasyBnE#1]
- [x] Account Creation
- [x] Log-in/Log-out 
- [ ] Demo login 
- [ ] Adequate Styling 
- [ ] Smooth bug-free navigation

**Comment by d-webs** [comment]
Nice! Can you make these changes? 

+ We're making a clone of AirBnB, which means _everything_ (including colors) has to match up. Unfortunately, that means the NavBar cannot be that color. Please have it match AirBnb's!

+ Right now, you are pre-filling the form-fields with actual text values. Instead, can you have the initial state be empty? If you want to show default values, you can use the placeholder flag. Like this: `<input value={this.state.username} placeholder="Email" />`

+ Your button to close the modal currently stretches across the entire modal box:
![screen shot 2018-04-06 at 9 58 20 am](https://user-images.githubusercontent.com/29282483/38433834-2b61f236-3981-11e8-9f68-997ea73d612b.png)

    Can you A) change it so that it only takes up the top-left corner (Right now, if I click anywhere up 
    there the modal closes) and B) Change the font? I noticed you tried to make it `helvetica`, but it 
    didn't take. This is because the css attribute has to be `font-family` not just `font`. 

+ Users should not have to input their name ("What should we call you") on the 'Login' form— only the signup form.

+ Currently getting errors on the demo login. This is likely because the Demo User does not exist in your `production` database. Remember, these are two completely separate databases. 

Please make these changes! If you have any questions, please let me know.
