### ISSUE TITLE
Listings

### ISSUE THREAD

**Issue by AbstractRamen** [AbstractRamen/FantasyBnE#3]
- [x] Create/View for user listings
- [x] Listing creation is protected
- [x] Users can upload photos for listings
- [x] Adequate Styling
- [x] Smooth, bug-free navigation
- [x] Seeded with information to demonstrate feature

**Comment by d-webs** [comment]
Can you add the following styling changes?

+ In your `ul-wrapper` css class (the one that holds the listing index), change it to be `justify-content: left`

+ Then, on every `listing-index-item`, give it `margin-left: 20px` so that they are spaced out.

See how, after doing this, the ones at the bottom aren't floating in the middle?
